// ===================================
// Main.cpp file generated by OptFrame
// Project NumberPartitionProblem
// ===================================

#include <iostream>
#include <iomanip>
#include <fstream>
#include <memory>
#include <utility>
#include <tuple>
#include <chrono>
#include <future>

#include <sys/types.h>
#include <dirent.h>

#include <stdlib.h>
#include <math.h>

#include "OptFrame/Heuristics/SA/BasicSimulatedAnnealing.hpp"
#include "OptFrame/Heuristics/LocalSearches/BestImprovement.hpp"
#include "OptFrame/Heuristics/LocalSearches/FirstImprovement.hpp"
#include "OptFrame/Heuristics/LocalSearches/HillClimbing.hpp"
#include "OptFrame/Heuristics/LocalSearches/RandomDescentMethod.hpp"
#include "OptFrame/Util/CheckCommand.hpp"
#include "OptFrame/SingleObjSearch.hpp"
#include "OptFrame/Util/RandGenMersenneTwister.hpp"
#include "OptFrame/Util/printable.h"

#include "NPP.h"
#include "NPP/SolvingMethod.h"

using namespace std;
using namespace optframe;
using namespace NPP;

void check(RandGenMersenneTwister &rg) {
    // Initialize here all your OptFrame components
    // (ProblemInstance, Evaluator, Constructive, ...)
    unique_ptr<ifstream> ifs(new std::ifstream("input/example.in", std::ifstream::in));
    Scanner scanner(ifs.get());
    ProblemInstance p(scanner);

    CheckCommand<RepNPP> check;
    MyEvaluator ev(p);
    check.add(ev);

    ConstructiveGreedy c1(p);
    ConstructiveRand c2(p, rg);
    check.add(c1);
    check.add(c2);

    NSSeqBitFlip ns1(p, rg);
    check.add(ns1);

    check.run(10, 10);
}

int main(int argc, char **argv) {
    RandGenMersenneTwister rg; // not using system rand() anymore
    check(rg);

    string folder = "input";
    DIR *dirp = opendir(folder.c_str());
    struct dirent *dp;
    cout << "file;SA;timeSA;LS;timeLS" << endl;
    while ((dp = readdir(dirp)) != nullptr) {
        string file = dp->d_name;
        if (file != "." && file != ".." && file != "example.in" && file.find_last_of(".in") == file.length() - 1) {
            cerr << file << endl;
            for (int cont = 0; cont < 30; ++cont) {
                auto resp = solveSA(rg, folder + "/" + file);
                cout <<
                     file << ";" <<
                     std::fixed << std::setprecision(0) << get<1>(resp).evaluation() << ";" <<
                     std::fixed << std::setprecision(5) << get<2>(resp) << ";" <<
                     std::fixed << std::setprecision(0) << get<4>(resp).evaluation() << ";" <<
                     std::fixed << std::setprecision(5) << get<5>(resp) << "" <<
                     endl;
            }
        }
    }
    closedir(dirp);

    cout << "Program ended successfully" << endl;

    return 0;
}
